services:
  wordpress:
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "8123:80"
    environment:
      WORDPRESS_SITE_URL: http://localhost:8123
      FS_METHOD: direct
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"
      
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
volumes:
  site-data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.91.0/24
