

app = 'docker-wordpress-sqlite'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  protocol = 'tcp'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[services]]
  internal_port = 80
  protocol = 'tcp'

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[env]
  WORDPRESS_SITE_URL = 'https://docker-wordpress-sqlite.fly.dev'
  FS_METHOD = 'direct'